name: Build and push docker image
on:
  push:
    branches:
      - stable
      - unstable
    tags:
      - '*'

jobs:
  build:
    name: Create docker images
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout sources
          uses: actions/checkout@v2.2.0
          with:
            fetch-depth: 0

        - name: Login to registries
          shell: bash
          run: |
            echo "${{ secrets.QUAY_PASSWORD }}" | docker login -u "${{ secrets.QUAY_USERNAME }}" --password-stdin quay.io
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ghcr.io

        - name: Convert GITHUB_REPOSITORY into lowercase
          run: |
            echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

        - name: Get the version
          id: vars
          shell: bash
          run: |
            TAG=$(git tag -l | sort -V | tail -n 1)
            BRANCH="$(git rev-parse --abbrev-ref HEAD)"
            if [ "${BRANCH}" != "stable" ]; then
              TAG="${BRANCH}"
            elif [ "${TAG}" != "$(git describe --tags)" ]; then
              TAG="${BRANCH}"
            fi
            echo ::set-output name=tag::$(echo ${TAG})
            echo ::set-output name=branch::$(echo ${BRANCH})

        - name: Build the docker image for x86_64
          shell: bash
          run: |
            docker build --file Dockerfile \
              --tag "quay.io/${{ secrets.QUAY_USERNAME }}/ao-chat-websocket-proxy:${{steps.vars.outputs.tag}}" \
              --tag "quay.io/${{ secrets.QUAY_USERNAME }}/ao-chat-websocket-proxy:${{steps.vars.outputs.branch}}" \
              --tag "ghcr.io/${REPO}:${{steps.vars.outputs.tag}}" \
              --tag "ghcr.io/${REPO}:${{steps.vars.outputs.branch}}" .

        - name: Push the tagged Docker image
          shell: bash
          run: |
            docker push "quay.io/${{ secrets.QUAY_USERNAME }}/ao-chat-websocket-proxy:${{steps.vars.outputs.tag}}"
            docker push "quay.io/${{ secrets.QUAY_USERNAME }}/ao-chat-websocket-proxy:${{steps.vars.outputs.branch}}"
            docker push "ghcr.io/${REPO}:${{steps.vars.outputs.tag}}"
            docker push "ghcr.io/${REPO}:${{steps.vars.outputs.branch}}"
